add logic for requiring config file for image builds
Signed-off-by: Jordan Dubrick <jdubrick@redhat.com>

diff --git a/.github/workflows/validate-build.yml b/.github/workflows/validate-build.yml
--- a/.github/workflows/validate-build.yml
+++ b/.github/workflows/validate-build.yml
@@ -30,7 +30,10 @@ jobs:
         for dir in ${ALL_CHANGED_FILES}; do
             echo "Change detected in $dir ..."
             cd $dir
-            if [ ! -f config.env ]; then
+            if [ ! -f config.env ] && ([ -f Dockerfile ] || [ -f Containerfile ]); then
+                echo "No config.env file present in changed directory that contains image files. Throwing error ..."
+                exit 1
+            elif [ ! -f config.env ]; then
                 echo "No config.env file present in changed directory, skipping ..."
                 cd $BASE_DIR
                 continue
